{% set name = "tabula-py" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e47f1e08472f5a2942857d7cfe4811c36351bb4bfb7660032a517025b4d77c6

build:
  number: 0
  skip: true  # [py2k]
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - flake8
    - setuptools
    - setuptools_scm
  run:
    - python
    - pandas
    - numpy
    - requests
    - distro  # [linux]
    - openjdk
    - setuptools
    - setuptools_scm

test:
  imports:
    - tabula

about:
  home: https://github.com/chezou/tabula-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple wrapper of tabula-java: extract table from PDF into pandas DataFrame'
  description: |
    tabula-py is a simple Python wrapper of tabula-java, which can read 
    table of PDF. You can read tables from PDF and convert into pandas's 
    DataFrame. tabula-py also enables you to convert a PDF file into 
    CSV/TSV/JSON file.
  doc_url: https://tabula.technology/
  dev_url: https://github.com/chezou/tabula-py

extra:
  recipe-maintainers:
    - CurtLH
    - sodre
    - tpmusielak
