{% set name = "tabula-py" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29a032921d177f78c8ad2d4641c85a6ea63b570211d4f552a156a3dca23e9cb3

build:
  number: 0
  skip: True  # [py2k]
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - flake8
  run:
    - python
    - pandas
    - numpy
    - requests
    - distro  # [linux]
    - openjdk

test:
  imports:
    - tabula

about:
  home: https://github.com/chezou/tabula-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple wrapper of tabula-java: extract table from PDF into pandas DataFrame'
  description: |
    tabula-py is a simple Python wrapper of tabula-java, which can read 
    table of PDF. You can read tables from PDF and convert into pandas's 
    DataFrame. tabula-py also enables you to convert a PDF file into 
    CSV/TSV/JSON file.
  doc_url: https://tabula.technology/
  dev_url: https://github.com/chezou/tabula-py

extra:
  recipe-maintainers:
    - CurtLH
    - sodre
